// 每日語錄：公版古文＋自寫短句；每日試煉；回合後小提示
const QUOTES = [
  ['不積跬步，無以至千里。', '荀子'],
  ['學而不思則罔，思而不學則殆。', '論語'],
  ['用志不分，乃凝於神。', '莊子'],
  ['知止而後有定，定而後能靜。', '大學'],
  ['騏驥一躍，不能十步；駑馬十駕，功在不舍。', '荀子'],
  ['心不在焉，視而不見，聽而不聞。', '大學'],
  ['靜以修身，儉以養德。', '諸葛亮'],
  ['非寧靜無以致遠。', '諸葛亮'],
  ['鍥而不舍，金石可鏤。', '荀子'],
  ['吾日三省吾身。', '論語'],
  ['君子欲訥於言而敏於行。', '論語'],
  ['水之積也不厚，則其負大舟也無力。', '莊子'],
  ['工欲善其事，必先利其器。', '論語'],
  ['其身正，不令而行。', '論語'],
  ['千里之行，始於足下。', '老子'],
  ['大道甚夷，而民好徑。', '老子'],
  ['此心不動，隨機而動。', '王陽明'],
  ['事上磨練，方立得住。', '王陽明'],
  ['主一無適之謂敬。', '程頤'],
  ['業精於勤，荒於嬉。', '韓愈'],
  ['這裡沒有排行榜，只有昨天的你。', '道場'],
  ['分心不是失敗，是一筆資料。', '道場'],
  ['想到的事先停車，坐完再處理。', '道場'],
  ['一坐 25 分，比想一整天更接近完成。', '道場'],
  ['手機翻面，是今天最便宜的勝利。', '道場'],
  ['做滿 5 分鐘，門就開了。', '道場'],
  ['專注不是用力，是把別的門先關上。', '道場'],
  ['段位會掉，但只要回來坐，它就回來。', '道場'],
  ['記錄第幾分鐘分心，比記錄分心幾次更有用。', '道場'],
  ['今天的坐，是明天的本錢。', '道場'],
];

// 每日試煉：依日期固定一題；check(ctx) 回傳是否達成
const TRIALS = [
  { id: 'zero25', name: '清淨一坐', desc: '完成一坐 ≥25 分且零分心', check: c => c.sessions.some(s => s.completed && s.actual >= 1500 && s.distractions.length === 0) },
  { id: 'long45', name: '長坐', desc: '完成一坐 ≥45 分', check: c => c.sessions.some(s => s.completed && s.actual >= 2700) },
  { id: 'two', name: '連坐兩回', desc: '今天完成兩坐', check: c => c.sessions.filter(s => s.completed).length >= 2 },
  { id: 'breath', name: '先吐納後坐', desc: '先呼吸 ≥3 分，再完成一坐', check: c => c.breaths.some(b => b.seconds >= 180) && c.sessions.some(s => s.completed) },
  { id: 'intent', name: '立意而坐', desc: '寫下意圖再完成一坐', check: c => c.sessions.some(s => s.completed && (s.outcome || s.ifthen)) },
  { id: 'stroop', name: '心如止水', desc: 'Stroop 干擾量 <120 ms', check: c => c.games.some(g => g.type === 'stroop' && g.interference != null && g.interference < 120) },
  { id: 'schulte', name: '眼明手快', desc: '舒爾特方格 <30 秒', check: c => c.games.some(g => g.type === 'schulte' && g.ms < 30000) },
  { id: 'park', name: '停車入庫', desc: '一坐中停車一個念頭並完成', check: c => c.sessions.some(s => s.completed && (s.parked || []).length) },
  { id: 'review', name: '自省', desc: '完成一坐並給出品質評分', check: c => c.sessions.some(s => s.completed && s.quality) },
  { id: 'one', name: '容錯一坐', desc: '完成一坐 ≥25 分且分心 ≤1', check: c => c.sessions.some(s => s.completed && s.actual >= 1500 && s.distractions.length <= 1) },
];

const TIPS = [
  '下一坐試試：手機放到另一個房間。',
  '下一坐試試：開始前把桌上只留一樣東西。',
  '下一坐試試：先寫下「做完的樣子」再按開始。',
  '下一坐試試：縮短 5 分鐘，換取零分心。',
  '下一坐試試：分心時只做一件事——記下來，不處理。',
  '下一坐試試：先呼吸 3 分鐘，心跳慢下來再坐。',
  '下一坐試試：把「若分心→我會…」寫得更具體。',
  '下一坐試試：關掉所有通知，連電腦的也關。',
  '下一坐試試：在同一個時段、同一個位置坐。',
  '下一坐試試：坐前喝水，坐中不離座。',
];
